export const BOT_CONFIG = {
    BOT_TOKEN: import.meta.env.VITE_BOT_TOKEN || 'YOUR_BOT_TOKEN',
    BOT_USERNAME: import.meta.env.VITE_BOT_USERNAME || 'YOUR_BOT_USERNAME',
    SYNC_INTERVAL: 2000,
    RETRY_ATTEMPTS: 3
}; 